apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lgtm-lbac-proxy.name" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lgtm-lbac-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "lgtm-lbac-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lgtm-lbac-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lgtm-lbac-proxy.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range . }}
        - {{- toYaml . | nindent 10 }}
          labelSelector:
            matchLabels:
              {{- include "lgtm-lbac-proxy.selectorLabels" $ | nindent 14 }}
        {{- end }}
      {{- end }}
      containers:
        - name: proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent"  }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.webPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            {{- if .Values.resources.limits }}
            limits:
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.resources.limits.memory }}
              memory: {{ .Values.resources.limits.memory }}
              {{- end }}
            {{- end }}
          {{- if .Values.probes.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds  }}
          {{- end }}
          {{- if .Values.probes.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/config/config/
              name: config
            - mountPath: /etc/config/labels/
              name: labels
            {{- if eq .Values.tls.loki.enabled true }}
            - mountPath: /etc/secrets/ca/loki/
              name: loki-tls-secret
            {{- end }}
            {{- if eq .Values.tls.thanos.enabled true }}
            - mountPath: /etc/secrets/ca/thanos/
              name: thanos-tls-secret
            {{- end }}
            {{- if eq .Values.tls.tempo.enabled true }}
            - mountPath: /etc/secrets/ca/tempo/
              name: tempo-tls-secret
            {{- end }}
      volumes:
        - configMap:
            name: {{ include "lgtm-lbac-proxy.name" . }}-config
          name: config
        - configMap:
            name: {{ include "lgtm-lbac-proxy.name" . }}-labels
          name: labels
          {{- if eq .Values.tls.loki.enabled true }}
        - name: loki-tls-secret
          secret:
            secretName: {{ .Values.tls.loki.secretName }}
          {{- end }}
          {{- if eq .Values.tls.thanos.enabled true }}
        - name: thanos-tls-secret
          secret:
            secretName: {{ .Values.tls.thanos.secretName }}
          {{- end }}
          {{- if eq .Values.tls.tempo.enabled true }}
        - name: tempo-tls-secret
          secret:
            secretName: {{ .Values.tls.tempo.secretName }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
