{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "lgtm-lbac-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "lgtm-lbac-proxy.serviceAccountName" . }}-role-binding-monitoring-view
subjects:
  - kind: ServiceAccount
    name: {{ include "lgtm-lbac-proxy.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
---
{{- end}}