apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lgtm-lbac-proxy.name" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lgtm-lbac-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lgtm-lbac-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ include "lgtm-lbac-proxy.name" . }}-metrics
      interval: 15s
      path: /metrics