apiVersion: v1
kind: Service
metadata:
  name: {{ include "lgtm-lbac-proxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lgtm-lbac-proxy.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
      name: {{ include "lgtm-lbac-proxy.name" . }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: {{ include "lgtm-lbac-proxy.name" . }}-metrics
  selector:
    {{- include "lgtm-lbac-proxy.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
